# Generated by Django 3.2.15 on 2022-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
