# Generated by Django 4.1.3 on 2022-12-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_contactmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmodel",
            name="subject",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
