# Generated by Django 4.1.3 on 2022-12-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myfinance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
