# Generated by Django 3.2.15 on 2022-08-20 13:26

from django.db import migrations, models
import django.db.models.deletion
import myexpenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('myexpenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hyderabad Home', max_length=50)),
                ('comments', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(blank=True, default=myexpenses.models.Transaction.get_default_group, on_delete=django.db.models.deletion.PROTECT, to='myexpenses.group'),
        ),
    ]
